require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'coverage/**/*'
    - 'log/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'lib/templates/**/*'
    - 'lib/tasks/database.rake'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'db/schema.rb'
    - 'lib/heroku_app.rb'

Layout/LineLength:
  Max: 100

Layout/SpaceBeforeBrackets:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 30
  Exclude:
    - spec/system/*
    - 'app/commands/**/*_tables.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: false

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it', 'before', 'included']
  Exclude:
    - spec/*
    - lib/tasks/*

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/bulma/*
    - app/helpers/ransack/*
    - app/helpers/shared_form_builder_utils.rb

Rails/DynamicFindBy:
  Exclude:
    - app/commands/pm/initiatives_export.rb

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/inv/package_vendor.rb

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/**/*

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/RedundantBegin:
  Enabled: false
