name: Changelog Checker
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
jobs:
  build:
    name: Changelog Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: no-changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
