name: Cypress Tests
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run migrations
        run: bin/rails db:migrate RAILS_ENV=development

      - name: Install foreman gem
        run: gem install foreman

      - name: Install yarn and build
        run: |
          npm install -g yarn
          yarn install
          yarn build

      - name: Start server and run tests
        run: foreman start -f Procfile.dev
