name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby and gems
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        run: yarn cy:run
        with:
          browser: chrome
          headless: true
          start: bin/rails server -p 3000
          wait-on: 'http://localhost:3000'
