name: Cypress Tests
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: gem install foreman

      - run: |
          npm install -g yarn
          yarn install
          foreman start -f Procfile.dev
